<?xml version="1.0" encoding="utf-8"?><Database Name="webtour" Class="DataPhimDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-HEFMRGI\SQLEXPRESS;Initial Catalog=webtour;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="webtourConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tour" Member="Tours">
    <Type Name="Tour">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="khoiHanhTu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="thoiGian" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="khoiHangNgay" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="gioiThieuTuor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thumbnail" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="chuongtrinhtour" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="khuyenmai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="diemdenid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tenTour" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.orderTour" Member="orderTours">
    <Type Name="orderTour">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dienthoai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="khoiHangNgay" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="nguoilon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="treem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TTrongNuoc" Member="TTrongNuocs">
    <Type Name="TTrongNuoc">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="khoihanhtu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="thoigian" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="khoihangngay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gioithieutour" Type="System.String" DbType="NVarChar(3000)" CanBeNull="true" />
      <Column Name="thumbnail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="chuongtrinhtour" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="khuyenmai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diemdenid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tentour" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachSan" Member="KhachSans">
    <Type Name="KhachSan">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenkhachsan" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="loaiphong" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="songuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descript" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Newss" Member="Newsses">
    <Type Name="Newss">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="content" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="descriptions" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="photo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TNuocNgoai" Member="TNuocNgoais">
    <Type Name="TNuocNgoai">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="khoihanhtu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="thoigian" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="khoihanhngay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gioithieutour" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="thumbnail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="chuongtrinhtour" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="khuyenmai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diemdenid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gia" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="tentour" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThongTinXe" Member="ThongTinXes">
    <Type Name="ThongTinXe">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="loaixe" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="tuyenxe" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="dongia" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="descript" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>