#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteRapChieuPhim.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="webtour")]
	public partial class DataPhimDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTour(Tour instance);
    partial void UpdateTour(Tour instance);
    partial void DeleteTour(Tour instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertorderTour(orderTour instance);
    partial void UpdateorderTour(orderTour instance);
    partial void DeleteorderTour(orderTour instance);
    partial void InsertTTrongNuoc(TTrongNuoc instance);
    partial void UpdateTTrongNuoc(TTrongNuoc instance);
    partial void DeleteTTrongNuoc(TTrongNuoc instance);
    partial void InsertKhachSan(KhachSan instance);
    partial void UpdateKhachSan(KhachSan instance);
    partial void DeleteKhachSan(KhachSan instance);
    partial void InsertNewss(Newss instance);
    partial void UpdateNewss(Newss instance);
    partial void DeleteNewss(Newss instance);
    partial void InsertTNuocNgoai(TNuocNgoai instance);
    partial void UpdateTNuocNgoai(TNuocNgoai instance);
    partial void DeleteTNuocNgoai(TNuocNgoai instance);
    partial void InsertThongTinXe(ThongTinXe instance);
    partial void UpdateThongTinXe(ThongTinXe instance);
    partial void DeleteThongTinXe(ThongTinXe instance);
    #endregion
		
		public DataPhimDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["webtourConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataPhimDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataPhimDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataPhimDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataPhimDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tour> Tours
		{
			get
			{
				return this.GetTable<Tour>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<orderTour> orderTours
		{
			get
			{
				return this.GetTable<orderTour>();
			}
		}
		
		public System.Data.Linq.Table<TTrongNuoc> TTrongNuocs
		{
			get
			{
				return this.GetTable<TTrongNuoc>();
			}
		}
		
		public System.Data.Linq.Table<KhachSan> KhachSans
		{
			get
			{
				return this.GetTable<KhachSan>();
			}
		}
		
		public System.Data.Linq.Table<Newss> Newsses
		{
			get
			{
				return this.GetTable<Newss>();
			}
		}
		
		public System.Data.Linq.Table<TNuocNgoai> TNuocNgoais
		{
			get
			{
				return this.GetTable<TNuocNgoai>();
			}
		}
		
		public System.Data.Linq.Table<ThongTinXe> ThongTinXes
		{
			get
			{
				return this.GetTable<ThongTinXe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tour")]
	public partial class Tour : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _khoiHanhTu;
		
		private string _thoiGian;
		
		private string _khoiHangNgay;
		
		private string _gioiThieuTuor;
		
		private string _thumbnail;
		
		private string _chuongtrinhtour;
		
		private string _khuyenmai;
		
		private System.Nullable<int> _diemdenid;
		
		private string _gia;
		
		private string _tenTour;
		
		private EntitySet<TNuocNgoai> _TNuocNgoais;
		
		private EntitySet<TTrongNuoc> _TTrongNuocs;
		
		private EntityRef<orderTour> _orderTour;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkhoiHanhTuChanging(string value);
    partial void OnkhoiHanhTuChanged();
    partial void OnthoiGianChanging(string value);
    partial void OnthoiGianChanged();
    partial void OnkhoiHangNgayChanging(string value);
    partial void OnkhoiHangNgayChanged();
    partial void OngioiThieuTuorChanging(string value);
    partial void OngioiThieuTuorChanged();
    partial void OnthumbnailChanging(string value);
    partial void OnthumbnailChanged();
    partial void OnchuongtrinhtourChanging(string value);
    partial void OnchuongtrinhtourChanged();
    partial void OnkhuyenmaiChanging(string value);
    partial void OnkhuyenmaiChanged();
    partial void OndiemdenidChanging(System.Nullable<int> value);
    partial void OndiemdenidChanged();
    partial void OngiaChanging(string value);
    partial void OngiaChanged();
    partial void OntenTourChanging(string value);
    partial void OntenTourChanged();
    #endregion
		
		public Tour()
		{
			this._TNuocNgoais = new EntitySet<TNuocNgoai>(new Action<TNuocNgoai>(this.attach_TNuocNgoais), new Action<TNuocNgoai>(this.detach_TNuocNgoais));
			this._TTrongNuocs = new EntitySet<TTrongNuoc>(new Action<TTrongNuoc>(this.attach_TTrongNuocs), new Action<TTrongNuoc>(this.detach_TTrongNuocs));
			this._orderTour = default(EntityRef<orderTour>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoiHanhTu", DbType="NVarChar(100)")]
		public string khoiHanhTu
		{
			get
			{
				return this._khoiHanhTu;
			}
			set
			{
				if ((this._khoiHanhTu != value))
				{
					this.OnkhoiHanhTuChanging(value);
					this.SendPropertyChanging();
					this._khoiHanhTu = value;
					this.SendPropertyChanged("khoiHanhTu");
					this.OnkhoiHanhTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiGian", DbType="NVarChar(100)")]
		public string thoiGian
		{
			get
			{
				return this._thoiGian;
			}
			set
			{
				if ((this._thoiGian != value))
				{
					this.OnthoiGianChanging(value);
					this.SendPropertyChanging();
					this._thoiGian = value;
					this.SendPropertyChanged("thoiGian");
					this.OnthoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoiHangNgay", DbType="NVarChar(100)")]
		public string khoiHangNgay
		{
			get
			{
				return this._khoiHangNgay;
			}
			set
			{
				if ((this._khoiHangNgay != value))
				{
					this.OnkhoiHangNgayChanging(value);
					this.SendPropertyChanging();
					this._khoiHangNgay = value;
					this.SendPropertyChanged("khoiHangNgay");
					this.OnkhoiHangNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiThieuTuor", DbType="NVarChar(MAX)")]
		public string gioiThieuTuor
		{
			get
			{
				return this._gioiThieuTuor;
			}
			set
			{
				if ((this._gioiThieuTuor != value))
				{
					this.OngioiThieuTuorChanging(value);
					this.SendPropertyChanging();
					this._gioiThieuTuor = value;
					this.SendPropertyChanged("gioiThieuTuor");
					this.OngioiThieuTuorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thumbnail", DbType="NVarChar(200)")]
		public string thumbnail
		{
			get
			{
				return this._thumbnail;
			}
			set
			{
				if ((this._thumbnail != value))
				{
					this.OnthumbnailChanging(value);
					this.SendPropertyChanging();
					this._thumbnail = value;
					this.SendPropertyChanged("thumbnail");
					this.OnthumbnailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuongtrinhtour", DbType="NVarChar(MAX)")]
		public string chuongtrinhtour
		{
			get
			{
				return this._chuongtrinhtour;
			}
			set
			{
				if ((this._chuongtrinhtour != value))
				{
					this.OnchuongtrinhtourChanging(value);
					this.SendPropertyChanging();
					this._chuongtrinhtour = value;
					this.SendPropertyChanged("chuongtrinhtour");
					this.OnchuongtrinhtourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khuyenmai", DbType="NVarChar(100)")]
		public string khuyenmai
		{
			get
			{
				return this._khuyenmai;
			}
			set
			{
				if ((this._khuyenmai != value))
				{
					this.OnkhuyenmaiChanging(value);
					this.SendPropertyChanging();
					this._khuyenmai = value;
					this.SendPropertyChanged("khuyenmai");
					this.OnkhuyenmaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemdenid", DbType="Int")]
		public System.Nullable<int> diemdenid
		{
			get
			{
				return this._diemdenid;
			}
			set
			{
				if ((this._diemdenid != value))
				{
					this.OndiemdenidChanging(value);
					this.SendPropertyChanging();
					this._diemdenid = value;
					this.SendPropertyChanged("diemdenid");
					this.OndiemdenidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="NVarChar(50)")]
		public string gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTour", DbType="NVarChar(200)")]
		public string tenTour
		{
			get
			{
				return this._tenTour;
			}
			set
			{
				if ((this._tenTour != value))
				{
					if (this._orderTour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntenTourChanging(value);
					this.SendPropertyChanging();
					this._tenTour = value;
					this.SendPropertyChanged("tenTour");
					this.OntenTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tour_TNuocNgoai", Storage="_TNuocNgoais", ThisKey="id,khoiHanhTu,thoiGian,khoiHangNgay,gioiThieuTuor,thumbnail,chuongtrinhtour,tenTo" +
			"ur,gia,diemdenid,khuyenmai", OtherKey="id,khoihanhtu,thoigian,khoihanhngay,gioithieutour,thumbnail,chuongtrinhtour,tento" +
			"ur,gia,diemdenid,khuyenmai")]
		public EntitySet<TNuocNgoai> TNuocNgoais
		{
			get
			{
				return this._TNuocNgoais;
			}
			set
			{
				this._TNuocNgoais.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tour_TTrongNuoc", Storage="_TTrongNuocs", ThisKey="id,khoiHanhTu,thoiGian,khoiHangNgay,gioiThieuTuor,thumbnail,chuongtrinhtour,khuye" +
			"nmai,diemdenid,gia,tenTour", OtherKey="Id,khoihanhtu,thoigian,khoihangngay,gioithieutour,thumbnail,chuongtrinhtour,khuye" +
			"nmai,diemdenid,gia,tentour")]
		public EntitySet<TTrongNuoc> TTrongNuocs
		{
			get
			{
				return this._TTrongNuocs;
			}
			set
			{
				this._TTrongNuocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="orderTour_Tour", Storage="_orderTour", ThisKey="tenTour", OtherKey="tentour", IsForeignKey=true)]
		public orderTour orderTour
		{
			get
			{
				return this._orderTour.Entity;
			}
			set
			{
				orderTour previousValue = this._orderTour.Entity;
				if (((previousValue != value) 
							|| (this._orderTour.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._orderTour.Entity = null;
						previousValue.Tours.Remove(this);
					}
					this._orderTour.Entity = value;
					if ((value != null))
					{
						value.Tours.Add(this);
						this._tenTour = value.tentour;
					}
					else
					{
						this._tenTour = default(string);
					}
					this.SendPropertyChanged("orderTour");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TNuocNgoais(TNuocNgoai entity)
		{
			this.SendPropertyChanging();
			entity.Tour = this;
		}
		
		private void detach_TNuocNgoais(TNuocNgoai entity)
		{
			this.SendPropertyChanging();
			entity.Tour = null;
		}
		
		private void attach_TTrongNuocs(TTrongNuoc entity)
		{
			this.SendPropertyChanging();
			entity.Tour = this;
		}
		
		private void detach_TTrongNuocs(TTrongNuoc entity)
		{
			this.SendPropertyChanging();
			entity.Tour = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _name;
		
		private string _username;
		
		private string _password;
		
		private System.Nullable<int> _status;
		
		private System.Nullable<bool> _isAdmin;
		
		private string _email;
		
		private string _phone;
		
		private EntitySet<orderTour> _orderTours;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void OnisAdminChanging(System.Nullable<bool> value);
    partial void OnisAdminChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    #endregion
		
		public NguoiDung()
		{
			this._orderTours = new EntitySet<orderTour>(new Action<orderTour>(this.attach_orderTours), new Action<orderTour>(this.detach_orderTours));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isAdmin", DbType="Bit")]
		public System.Nullable<bool> isAdmin
		{
			get
			{
				return this._isAdmin;
			}
			set
			{
				if ((this._isAdmin != value))
				{
					this.OnisAdminChanging(value);
					this.SendPropertyChanging();
					this._isAdmin = value;
					this.SendPropertyChanged("isAdmin");
					this.OnisAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(50)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_orderTour", Storage="_orderTours", ThisKey="email", OtherKey="email")]
		public EntitySet<orderTour> orderTours
		{
			get
			{
				return this._orderTours;
			}
			set
			{
				this._orderTours.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_orderTours(orderTour entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_orderTours(orderTour entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.orderTour")]
	public partial class orderTour : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _hoten;
		
		private string _diachi;
		
		private string _email;
		
		private string _dienthoai;
		
		private string _khoiHangNgay;
		
		private string _nguoilon;
		
		private string _note;
		
		private string _treem;
		
		private EntitySet<Tour> _Tours;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndienthoaiChanging(string value);
    partial void OndienthoaiChanged();
    partial void OnkhoiHangNgayChanging(string value);
    partial void OnkhoiHangNgayChanged();
    partial void OnnguoilonChanging(string value);
    partial void OnnguoilonChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    partial void OntentourChanging(string value);
    partial void OntentourChanged();
    #endregion
		
		public orderTour()
		{
			this._Tours = new EntitySet<Tour>(new Action<Tour>(this.attach_Tours), new Action<Tour>(this.detach_Tours));
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(100)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienthoai", DbType="NVarChar(100)")]
		public string dienthoai
		{
			get
			{
				return this._dienthoai;
			}
			set
			{
				if ((this._dienthoai != value))
				{
					this.OndienthoaiChanging(value);
					this.SendPropertyChanging();
					this._dienthoai = value;
					this.SendPropertyChanged("dienthoai");
					this.OndienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoiHangNgay", DbType="NVarChar(100)")]
		public string khoiHangNgay
		{
			get
			{
				return this._khoiHangNgay;
			}
			set
			{
				if ((this._khoiHangNgay != value))
				{
					this.OnkhoiHangNgayChanging(value);
					this.SendPropertyChanging();
					this._khoiHangNgay = value;
					this.SendPropertyChanged("khoiHangNgay");
					this.OnkhoiHangNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoilon", DbType="NVarChar(50)")]
		public string nguoilon
		{
			get
			{
				return this._nguoilon;
			}
			set
			{
				if ((this._nguoilon != value))
				{
					this.OnnguoilonChanging(value);
					this.SendPropertyChanging();
					this._nguoilon = value;
					this.SendPropertyChanged("nguoilon");
					this.OnnguoilonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="NVarChar(1000)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="treem", Storage="_treem", DbType="NVarChar(50)")]
		public string tentour
		{
			get
			{
				return this._treem;
			}
			set
			{
				if ((this._treem != value))
				{
					this.OntentourChanging(value);
					this.SendPropertyChanging();
					this._treem = value;
					this.SendPropertyChanged("tentour");
					this.OntentourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="orderTour_Tour", Storage="_Tours", ThisKey="tentour", OtherKey="tenTour")]
		public EntitySet<Tour> Tours
		{
			get
			{
				return this._Tours;
			}
			set
			{
				this._Tours.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_orderTour", Storage="_NguoiDung", ThisKey="email", OtherKey="email", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.orderTours.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.orderTours.Add(this);
						this._email = value.email;
					}
					else
					{
						this._email = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tours(Tour entity)
		{
			this.SendPropertyChanging();
			entity.orderTour = this;
		}
		
		private void detach_Tours(Tour entity)
		{
			this.SendPropertyChanging();
			entity.orderTour = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTrongNuoc")]
	public partial class TTrongNuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _khoihanhtu;
		
		private string _thoigian;
		
		private string _khoihangngay;
		
		private string _gioithieutour;
		
		private string _thumbnail;
		
		private string _chuongtrinhtour;
		
		private string _khuyenmai;
		
		private System.Nullable<int> _diemdenid;
		
		private string _gia;
		
		private string _tentour;
		
		private EntityRef<Tour> _Tour;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnkhoihanhtuChanging(string value);
    partial void OnkhoihanhtuChanged();
    partial void OnthoigianChanging(string value);
    partial void OnthoigianChanged();
    partial void OnkhoihangngayChanging(string value);
    partial void OnkhoihangngayChanged();
    partial void OngioithieutourChanging(string value);
    partial void OngioithieutourChanged();
    partial void OnthumbnailChanging(string value);
    partial void OnthumbnailChanged();
    partial void OnchuongtrinhtourChanging(string value);
    partial void OnchuongtrinhtourChanged();
    partial void OnkhuyenmaiChanging(string value);
    partial void OnkhuyenmaiChanged();
    partial void OndiemdenidChanging(System.Nullable<int> value);
    partial void OndiemdenidChanged();
    partial void OngiaChanging(string value);
    partial void OngiaChanged();
    partial void OntentourChanging(string value);
    partial void OntentourChanged();
    #endregion
		
		public TTrongNuoc()
		{
			this._Tour = default(EntityRef<Tour>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoihanhtu", DbType="NVarChar(50)")]
		public string khoihanhtu
		{
			get
			{
				return this._khoihanhtu;
			}
			set
			{
				if ((this._khoihanhtu != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkhoihanhtuChanging(value);
					this.SendPropertyChanging();
					this._khoihanhtu = value;
					this.SendPropertyChanged("khoihanhtu");
					this.OnkhoihanhtuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigian", DbType="NVarChar(50)")]
		public string thoigian
		{
			get
			{
				return this._thoigian;
			}
			set
			{
				if ((this._thoigian != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnthoigianChanging(value);
					this.SendPropertyChanging();
					this._thoigian = value;
					this.SendPropertyChanged("thoigian");
					this.OnthoigianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoihangngay", DbType="NVarChar(50)")]
		public string khoihangngay
		{
			get
			{
				return this._khoihangngay;
			}
			set
			{
				if ((this._khoihangngay != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkhoihangngayChanging(value);
					this.SendPropertyChanging();
					this._khoihangngay = value;
					this.SendPropertyChanged("khoihangngay");
					this.OnkhoihangngayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioithieutour", DbType="NVarChar(3000)")]
		public string gioithieutour
		{
			get
			{
				return this._gioithieutour;
			}
			set
			{
				if ((this._gioithieutour != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OngioithieutourChanging(value);
					this.SendPropertyChanging();
					this._gioithieutour = value;
					this.SendPropertyChanged("gioithieutour");
					this.OngioithieutourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thumbnail", DbType="NVarChar(50)")]
		public string thumbnail
		{
			get
			{
				return this._thumbnail;
			}
			set
			{
				if ((this._thumbnail != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnthumbnailChanging(value);
					this.SendPropertyChanging();
					this._thumbnail = value;
					this.SendPropertyChanged("thumbnail");
					this.OnthumbnailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuongtrinhtour", DbType="NVarChar(MAX)")]
		public string chuongtrinhtour
		{
			get
			{
				return this._chuongtrinhtour;
			}
			set
			{
				if ((this._chuongtrinhtour != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnchuongtrinhtourChanging(value);
					this.SendPropertyChanging();
					this._chuongtrinhtour = value;
					this.SendPropertyChanged("chuongtrinhtour");
					this.OnchuongtrinhtourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khuyenmai", DbType="NVarChar(50)")]
		public string khuyenmai
		{
			get
			{
				return this._khuyenmai;
			}
			set
			{
				if ((this._khuyenmai != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkhuyenmaiChanging(value);
					this.SendPropertyChanging();
					this._khuyenmai = value;
					this.SendPropertyChanged("khuyenmai");
					this.OnkhuyenmaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemdenid", DbType="Int")]
		public System.Nullable<int> diemdenid
		{
			get
			{
				return this._diemdenid;
			}
			set
			{
				if ((this._diemdenid != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndiemdenidChanging(value);
					this.SendPropertyChanging();
					this._diemdenid = value;
					this.SendPropertyChanged("diemdenid");
					this.OndiemdenidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="NVarChar(50)")]
		public string gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentour", DbType="NVarChar(2000)")]
		public string tentour
		{
			get
			{
				return this._tentour;
			}
			set
			{
				if ((this._tentour != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntentourChanging(value);
					this.SendPropertyChanging();
					this._tentour = value;
					this.SendPropertyChanged("tentour");
					this.OntentourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tour_TTrongNuoc", Storage="_Tour", ThisKey="Id,khoihanhtu,thoigian,khoihangngay,gioithieutour,thumbnail,chuongtrinhtour,khuye" +
			"nmai,diemdenid,gia,tentour", OtherKey="id,khoiHanhTu,thoiGian,khoiHangNgay,gioiThieuTuor,thumbnail,chuongtrinhtour,khuye" +
			"nmai,diemdenid,gia,tenTour", IsForeignKey=true)]
		public Tour Tour
		{
			get
			{
				return this._Tour.Entity;
			}
			set
			{
				Tour previousValue = this._Tour.Entity;
				if (((previousValue != value) 
							|| (this._Tour.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tour.Entity = null;
						previousValue.TTrongNuocs.Remove(this);
					}
					this._Tour.Entity = value;
					if ((value != null))
					{
						value.TTrongNuocs.Add(this);
						this._Id = value.id;
						this._khoihanhtu = value.khoiHanhTu;
						this._thoigian = value.thoiGian;
						this._khoihangngay = value.khoiHangNgay;
						this._gioithieutour = value.gioiThieuTuor;
						this._thumbnail = value.thumbnail;
						this._chuongtrinhtour = value.chuongtrinhtour;
						this._khuyenmai = value.khuyenmai;
						this._diemdenid = value.diemdenid;
						this._gia = value.gia;
						this._tentour = value.tenTour;
					}
					else
					{
						this._Id = default(int);
						this._khoihanhtu = default(string);
						this._thoigian = default(string);
						this._khoihangngay = default(string);
						this._gioithieutour = default(string);
						this._thumbnail = default(string);
						this._chuongtrinhtour = default(string);
						this._khuyenmai = default(string);
						this._diemdenid = default(Nullable<int>);
						this._gia = default(string);
						this._tentour = default(string);
					}
					this.SendPropertyChanged("Tour");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachSan")]
	public partial class KhachSan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _tenkhachsan;
		
		private string _diachi;
		
		private string _loaiphong;
		
		private System.Nullable<int> _songuoi;
		
		private string _descript;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OntenkhachsanChanging(string value);
    partial void OntenkhachsanChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnloaiphongChanging(string value);
    partial void OnloaiphongChanged();
    partial void OnsonguoiChanging(System.Nullable<int> value);
    partial void OnsonguoiChanged();
    partial void OndescriptChanging(string value);
    partial void OndescriptChanged();
    #endregion
		
		public KhachSan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkhachsan", DbType="NVarChar(1000)")]
		public string tenkhachsan
		{
			get
			{
				return this._tenkhachsan;
			}
			set
			{
				if ((this._tenkhachsan != value))
				{
					this.OntenkhachsanChanging(value);
					this.SendPropertyChanging();
					this._tenkhachsan = value;
					this.SendPropertyChanged("tenkhachsan");
					this.OntenkhachsanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(1000)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiphong", DbType="NVarChar(500)")]
		public string loaiphong
		{
			get
			{
				return this._loaiphong;
			}
			set
			{
				if ((this._loaiphong != value))
				{
					this.OnloaiphongChanging(value);
					this.SendPropertyChanging();
					this._loaiphong = value;
					this.SendPropertyChanged("loaiphong");
					this.OnloaiphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_songuoi", DbType="Int")]
		public System.Nullable<int> songuoi
		{
			get
			{
				return this._songuoi;
			}
			set
			{
				if ((this._songuoi != value))
				{
					this.OnsonguoiChanging(value);
					this.SendPropertyChanging();
					this._songuoi = value;
					this.SendPropertyChanged("songuoi");
					this.OnsonguoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descript", DbType="NVarChar(MAX)")]
		public string descript
		{
			get
			{
				return this._descript;
			}
			set
			{
				if ((this._descript != value))
				{
					this.OndescriptChanging(value);
					this.SendPropertyChanging();
					this._descript = value;
					this.SendPropertyChanged("descript");
					this.OndescriptChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Newss")]
	public partial class Newss : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _title;
		
		private string _content;
		
		private string _descriptions;
		
		private string _photo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    partial void OndescriptionsChanging(string value);
    partial void OndescriptionsChanged();
    partial void OnphotoChanging(string value);
    partial void OnphotoChanged();
    #endregion
		
		public Newss()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(1000)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(1000)")]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this.OncontentChanging(value);
					this.SendPropertyChanging();
					this._content = value;
					this.SendPropertyChanged("content");
					this.OncontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descriptions", DbType="NVarChar(MAX)")]
		public string descriptions
		{
			get
			{
				return this._descriptions;
			}
			set
			{
				if ((this._descriptions != value))
				{
					this.OndescriptionsChanging(value);
					this.SendPropertyChanging();
					this._descriptions = value;
					this.SendPropertyChanged("descriptions");
					this.OndescriptionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo", DbType="NVarChar(50)")]
		public string photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				if ((this._photo != value))
				{
					this.OnphotoChanging(value);
					this.SendPropertyChanging();
					this._photo = value;
					this.SendPropertyChanged("photo");
					this.OnphotoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TNuocNgoai")]
	public partial class TNuocNgoai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _khoihanhtu;
		
		private string _thoigian;
		
		private string _khoihanhngay;
		
		private string _gioithieutour;
		
		private string _thumbnail;
		
		private string _chuongtrinhtour;
		
		private string _khuyenmai;
		
		private System.Nullable<int> _diemdenid;
		
		private string _gia;
		
		private string _tentour;
		
		private EntityRef<Tour> _Tour;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkhoihanhtuChanging(string value);
    partial void OnkhoihanhtuChanged();
    partial void OnthoigianChanging(string value);
    partial void OnthoigianChanged();
    partial void OnkhoihanhngayChanging(string value);
    partial void OnkhoihanhngayChanged();
    partial void OngioithieutourChanging(string value);
    partial void OngioithieutourChanged();
    partial void OnthumbnailChanging(string value);
    partial void OnthumbnailChanged();
    partial void OnchuongtrinhtourChanging(string value);
    partial void OnchuongtrinhtourChanged();
    partial void OnkhuyenmaiChanging(string value);
    partial void OnkhuyenmaiChanged();
    partial void OndiemdenidChanging(System.Nullable<int> value);
    partial void OndiemdenidChanged();
    partial void OngiaChanging(string value);
    partial void OngiaChanged();
    partial void OntentourChanging(string value);
    partial void OntentourChanged();
    #endregion
		
		public TNuocNgoai()
		{
			this._Tour = default(EntityRef<Tour>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoihanhtu", DbType="NVarChar(200)")]
		public string khoihanhtu
		{
			get
			{
				return this._khoihanhtu;
			}
			set
			{
				if ((this._khoihanhtu != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkhoihanhtuChanging(value);
					this.SendPropertyChanging();
					this._khoihanhtu = value;
					this.SendPropertyChanged("khoihanhtu");
					this.OnkhoihanhtuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigian", DbType="NVarChar(100)")]
		public string thoigian
		{
			get
			{
				return this._thoigian;
			}
			set
			{
				if ((this._thoigian != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnthoigianChanging(value);
					this.SendPropertyChanging();
					this._thoigian = value;
					this.SendPropertyChanged("thoigian");
					this.OnthoigianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoihanhngay", DbType="NVarChar(50)")]
		public string khoihanhngay
		{
			get
			{
				return this._khoihanhngay;
			}
			set
			{
				if ((this._khoihanhngay != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkhoihanhngayChanging(value);
					this.SendPropertyChanging();
					this._khoihanhngay = value;
					this.SendPropertyChanged("khoihanhngay");
					this.OnkhoihanhngayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioithieutour", DbType="NVarChar(4000)")]
		public string gioithieutour
		{
			get
			{
				return this._gioithieutour;
			}
			set
			{
				if ((this._gioithieutour != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OngioithieutourChanging(value);
					this.SendPropertyChanging();
					this._gioithieutour = value;
					this.SendPropertyChanged("gioithieutour");
					this.OngioithieutourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thumbnail", DbType="NVarChar(50)")]
		public string thumbnail
		{
			get
			{
				return this._thumbnail;
			}
			set
			{
				if ((this._thumbnail != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnthumbnailChanging(value);
					this.SendPropertyChanging();
					this._thumbnail = value;
					this.SendPropertyChanged("thumbnail");
					this.OnthumbnailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chuongtrinhtour", DbType="NVarChar(MAX)")]
		public string chuongtrinhtour
		{
			get
			{
				return this._chuongtrinhtour;
			}
			set
			{
				if ((this._chuongtrinhtour != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnchuongtrinhtourChanging(value);
					this.SendPropertyChanging();
					this._chuongtrinhtour = value;
					this.SendPropertyChanged("chuongtrinhtour");
					this.OnchuongtrinhtourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khuyenmai", DbType="NVarChar(50)")]
		public string khuyenmai
		{
			get
			{
				return this._khuyenmai;
			}
			set
			{
				if ((this._khuyenmai != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkhuyenmaiChanging(value);
					this.SendPropertyChanging();
					this._khuyenmai = value;
					this.SendPropertyChanged("khuyenmai");
					this.OnkhuyenmaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemdenid", DbType="Int")]
		public System.Nullable<int> diemdenid
		{
			get
			{
				return this._diemdenid;
			}
			set
			{
				if ((this._diemdenid != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndiemdenidChanging(value);
					this.SendPropertyChanging();
					this._diemdenid = value;
					this.SendPropertyChanged("diemdenid");
					this.OndiemdenidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="NVarChar(500)")]
		public string gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentour", DbType="NVarChar(4000)")]
		public string tentour
		{
			get
			{
				return this._tentour;
			}
			set
			{
				if ((this._tentour != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntentourChanging(value);
					this.SendPropertyChanging();
					this._tentour = value;
					this.SendPropertyChanged("tentour");
					this.OntentourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tour_TNuocNgoai", Storage="_Tour", ThisKey="id,khoihanhtu,thoigian,khoihanhngay,gioithieutour,thumbnail,chuongtrinhtour,tento" +
			"ur,gia,diemdenid,khuyenmai", OtherKey="id,khoiHanhTu,thoiGian,khoiHangNgay,gioiThieuTuor,thumbnail,chuongtrinhtour,tenTo" +
			"ur,gia,diemdenid,khuyenmai", IsForeignKey=true)]
		public Tour Tour
		{
			get
			{
				return this._Tour.Entity;
			}
			set
			{
				Tour previousValue = this._Tour.Entity;
				if (((previousValue != value) 
							|| (this._Tour.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tour.Entity = null;
						previousValue.TNuocNgoais.Remove(this);
					}
					this._Tour.Entity = value;
					if ((value != null))
					{
						value.TNuocNgoais.Add(this);
						this._id = value.id;
						this._khoihanhtu = value.khoiHanhTu;
						this._thoigian = value.thoiGian;
						this._khoihanhngay = value.khoiHangNgay;
						this._gioithieutour = value.gioiThieuTuor;
						this._thumbnail = value.thumbnail;
						this._chuongtrinhtour = value.chuongtrinhtour;
						this._tentour = value.tenTour;
						this._gia = value.gia;
						this._diemdenid = value.diemdenid;
						this._khuyenmai = value.khuyenmai;
					}
					else
					{
						this._id = default(int);
						this._khoihanhtu = default(string);
						this._thoigian = default(string);
						this._khoihanhngay = default(string);
						this._gioithieutour = default(string);
						this._thumbnail = default(string);
						this._chuongtrinhtour = default(string);
						this._tentour = default(string);
						this._gia = default(string);
						this._diemdenid = default(Nullable<int>);
						this._khuyenmai = default(string);
					}
					this.SendPropertyChanged("Tour");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinXe")]
	public partial class ThongTinXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _loaixe;
		
		private string _tuyenxe;
		
		private string _dongia;
		
		private string _image;
		
		private string _rate;
		
		private string _descript;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnloaixeChanging(string value);
    partial void OnloaixeChanged();
    partial void OntuyenxeChanging(string value);
    partial void OntuyenxeChanged();
    partial void OndongiaChanging(string value);
    partial void OndongiaChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnrateChanging(string value);
    partial void OnrateChanged();
    partial void OndescriptChanging(string value);
    partial void OndescriptChanged();
    #endregion
		
		public ThongTinXe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaixe", DbType="NVarChar(1000)")]
		public string loaixe
		{
			get
			{
				return this._loaixe;
			}
			set
			{
				if ((this._loaixe != value))
				{
					this.OnloaixeChanging(value);
					this.SendPropertyChanging();
					this._loaixe = value;
					this.SendPropertyChanged("loaixe");
					this.OnloaixeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tuyenxe", DbType="NVarChar(500)")]
		public string tuyenxe
		{
			get
			{
				return this._tuyenxe;
			}
			set
			{
				if ((this._tuyenxe != value))
				{
					this.OntuyenxeChanging(value);
					this.SendPropertyChanging();
					this._tuyenxe = value;
					this.SendPropertyChanged("tuyenxe");
					this.OntuyenxeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dongia", DbType="NVarChar(500)")]
		public string dongia
		{
			get
			{
				return this._dongia;
			}
			set
			{
				if ((this._dongia != value))
				{
					this.OndongiaChanging(value);
					this.SendPropertyChanging();
					this._dongia = value;
					this.SendPropertyChanged("dongia");
					this.OndongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(50)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rate", DbType="NVarChar(MAX)")]
		public string rate
		{
			get
			{
				return this._rate;
			}
			set
			{
				if ((this._rate != value))
				{
					this.OnrateChanging(value);
					this.SendPropertyChanging();
					this._rate = value;
					this.SendPropertyChanged("rate");
					this.OnrateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descript", DbType="NVarChar(MAX)")]
		public string descript
		{
			get
			{
				return this._descript;
			}
			set
			{
				if ((this._descript != value))
				{
					this.OndescriptChanging(value);
					this.SendPropertyChanging();
					this._descript = value;
					this.SendPropertyChanged("descript");
					this.OndescriptChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
